language: csharp
mono: none
sudo: required
solution: Blogs.Jhray
dist: bionic
dotnet: 3.1
addons:
 ssh_known_hosts: jhray.com
before_install:
 - bash Blogs.Jhray/_scripts/install.sh
script:
 - dotnet restore Blogs.Jhray/Blogs.Jhray.csproj
 - dotnet build Blogs.Jhray/Blogs.Jhray.csproj -c Release
after_success:
 - bash Blogs.Jhray/_scripts/deploy.sh
